### ISSUE TITLE
Better use of API status

### ISSUE THREAD

**Issue by masalmon** [ropensci/ropenaq#26]
I'd like to add a check of https://status.openaq.org/ in my code after I get a first error for a call. E.g. if the API health is bad, I should wait a bit / return NULL or something. I could also just wait but I think it's nicer if I can tell the user the reason why it's not working is the API status.

@jflasher which link should I query to get information from the status page? I looked at the source of the status page and it didn't make me any wiser :grin: I also tried to deduce the name of the endpoint / the URL from https://github.com/openaq/openaq-api/blob/2f7b0310fe59b63dc62d814301d5d36fe74eb226/api/routes/status.js and then I figured it'd be easier to ask :grimacing:

**Comment by masalmon** [comment]
@jflasher tagging you again ;-)

**Comment by jflasher** [comment]
You probably want https://api.openaq.org/status which currently just returns a red/yellow/green indication (coming from NewRelic). You could also look at https://api.openaq.org/v1/fetches and see that the latest data is being added correctly, but I think that's a bit of a different thing than what you're going for.

You could say something like:

green - probably no message needed since it's working fin
yellow - "there may be some slow down with the OpenAQ API"
red - "uh oh, the OpenAQ API seems to be having some issues, try again later"

**Comment by masalmon** [comment]
Awesome, thanks! I think your suggestion is great, I'll add it later this week. With yellow I'd keep trying with increasing waiting times, with red not. :grin:

**Comment by jflasher** [comment]
👍
