### ISSUE TITLE
look-up table for German cities contains wrong city names

### ISSUE THREAD

**Issue by birgitfullerton** [ropensci/ropenaq#39]
> aq_cities(country="DE")
# A tibble: 36 x 5
   city                      country locations  count cityURL                  
   <chr>                     <chr>       <int>  <int> <chr>                    
 1 Margit von Döhren         DE             27  21085 Margit+von+D%C3%B6hren   
 2 Heinz Ott                 DE             91 550810 Heinz+Ott                
 3 Annette Pausch            DE             34 216793 Annette+Pausch           
 4 Ingrid Zell               DE             17 107420 Ingrid+Zell              
 5 Ulrich Zimmermann         DE             27 263168 Ulrich+Zimmermann        
 6 Margit von D�hren         DE             27 312986 Margit+von+D%EF%BF%BDhren
 7 Andreas Hainsch           DE             38 309554 Andreas+Hainsch          
 8 Christiane Lutz-Holzhauer DE             54 325381 Christiane+Lutz-Holzhauer
 9 J�rgen Friesel            DE             62 353519 J%EF%BF%BDrgen+Friesel   
10 Thomas Draheim            DE             21 182497 Thomas+Draheim           
# ... with 26 more rows

**Comment by maelle** [comment]
Thanks a lot @birgitfullerton 😸  I think this is due to how the API got/structured the data. @jflasher where should I open an issue about this? openaq-fetch or openaq-api?

**Comment by jflasher** [comment]
Hi @birgitfullerton this is due to inconsistent use of the data fields coming from the EEA source initially. Issue was opened at https://github.com/openaq/openaq-fetch/issues/234. Their newer method of providing data does not have this issue, but we have historical data that'll need to be cleaned up. Tracking that at https://github.com/openaq/openaq-fetch/issues/478

Probably no reason for this issue to be open since it won't require any work for this project.

**Comment by maelle** [comment]
Thanks @flasher and thanks @birgitfullerton for the report!
